NumPy arrays are a powerful and efficient way to work with numerical data in Python. NumPy, short for Numerical Python, is a library that provides support for arrays, matrices, and many mathematical functions.

In [3]:
import numpy as np

list_data = [1,2,3,4,5]
array_from_list = np.array(list_data)

print(array_from_list)

[1 2 3 4 5]


In [5]:
# Create an zero array

import numpy as np

zero_array = np.zeros((3,3))

print(zero_array)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [6]:
# Creating an array of values only ones

import numpy as np

ones_array = np.ones((3,3))

print(ones_array)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [11]:
# Craeting a range of values

import numpy as np

range_array = np.arange(0,12,2)

print(range_array)

[ 0  2  4  6  8 10]


In [14]:
# Craeting a linespace array
import numpy as np

linespace_array = np.linspace(0,10,5)

print(linespace_array)

[ 0.   2.5  5.   7.5 10. ]


In [16]:
# array sum and product

import numpy as np

array1 = np.array([1,2,3,4,5])
array2 = np.array([1,2,3,4,5])

sum = array1 + array2

print(sum)

# product of array

product = array1 * array2

print(product)

[ 2  4  6  8 10]
[ 1  4  9 16 25]


In [17]:
# Mathematical functions 

import numpy as np

array = np.array([1,2,3,4,5])

sqrt_array = np.sqrt(array1)
sine_array = np.sin(array1)

print(sqrt_array)
print(sine_array)


[1.         1.41421356 1.73205081 2.         2.23606798]
[ 0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427]


In [22]:
# Array attributes
import numpy as np

# shape of the array
array = np.array([[1,2,3],[4,5,6]])

print(array.shape)

# number of dimensions

print(array.ndim)

# size of an array

print(array.size)

# Datatype of an array

print(array.dtype)


(2, 3)
2
6
int64


In [29]:
# Accessing array elements

import numpy as np

array = np.array([[1,2,3],[4,5,6]])

element = array[1, 2]

print(element)

subarray = array[:, 1:3]

print(subarray)

6
[[2 3]
 [5 6]]


In [30]:
# Broadcasting

import numpy as np

array1 = np.array([1,2,3])
array2 = np.array([[4],[5],[6]])

result = array1 + array2

print(result)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
